#Rund a postgres database with following values
#   username: user
#   password: password
#   database: chatpta_db
version: "3.9"
services:
  starter-api-express-test-db:
    image: postgres
    restart: always
    ports:
      - target: 5432
        published: 1111
    environment:
      POSTGRES_DB: chatpta_starter_db
      POSTGRES_USER: chatpta_starter_user
      POSTGRES_PASSWORD: password

  starter-api-express-development-db:
    image: postgres
    restart: always
    ports:
      - target: 5432
        published: 1222
    environment:
      POSTGRES_DB: chatpta_starter_db
      POSTGRES_USER: chatpta_starter_user
      POSTGRES_PASSWORD: password

  starter-api-express:
    build: .
    ports:
      - target: 3000
        published: 3000

