#Rund a postgres database with following values
#   username: user
#   password: password
#   database: chatpta_db
version: "3.9"
services:
  db:
    image: postgres
    restart: always
    ports:
      - target: 5432
        published: 5432
#        protocol: tcp
#        mode: host
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatpta_db
