#Rund a postgres database with following values
#   username: chatpta_starter_user
#   database: chatpta_starter_db
#   password: password
version: "3.9"
services:
  api-starter-express-test-db:
    image: postgres
    restart: always
    ports:
      - target: 5432
        published: 3111
    environment:
      POSTGRES_DB: chatpta_starter_db
      POSTGRES_USER: chatpta_starter_user
      POSTGRES_PASSWORD: password

  api-starter-express-development-db:
    image: postgres
    restart: always
    ports:
      - target: 5432
        published: 3222
    environment:
      POSTGRES_DB: chatpta_starter_db
      POSTGRES_USER: chatpta_starter_user
      POSTGRES_PASSWORD: password

  api-starter-express:
    build: .
    ports:
      - target: 3000
        published: 3000

